//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC18 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WC18.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Países afiliados.
        /// </summary>
        public static string Affiliates {
            get {
                return ResourceManager.GetString("Affiliates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseño Base.
        /// </summary>
        public static string BaseDesign {
            get {
                return ResourceManager.GetString("BaseDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizado por.
        /// </summary>
        public static string Customized {
            get {
                return ResourceManager.GetString("Customized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciencia de la fertilidad.
        /// </summary>
        public static string FertilityScience {
            get {
                return ResourceManager.GetString("FertilityScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferencia WOOMB.
        /// </summary>
        public static string Headerhome {
            get {
                return ResourceManager.GetString("Headerhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospedaje cortesía de.
        /// </summary>
        public static string Hosting {
            get {
                return ResourceManager.GetString("Hosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de ID es requerido..
        /// </summary>
        public static string IdNumberRequired {
            get {
                return ResourceManager.GetString("IdNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de ID debe tener entre {2} y {1} caracteres..
        /// </summary>
        public static string IdNumberStringLength {
            get {
                return ResourceManager.GetString("IdNumberStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de ID es requerido..
        /// </summary>
        public static string IdTypeRequired {
            get {
                return ResourceManager.GetString("IdTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlas Inspiradoras.
        /// </summary>
        public static string InspiringPresentations {
            get {
                return ResourceManager.GetString("InspiringPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LangComplement {
            get {
                return ResourceManager.GetString("LangComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información aquí.
        /// </summary>
        public static string LinkSponsors {
            get {
                return ResourceManager.GetString("LinkSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscripción.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panelistas.
        /// </summary>
        public static string Speakers {
            get {
                return ResourceManager.GetString("Speakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrocinadores.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamientos de instructores.
        /// </summary>
        public static string TeacherEducation {
            get {
                return ResourceManager.GetString("TeacherEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión Español.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English version.
        /// </summary>
        public static string VersionComplement {
            get {
                return ResourceManager.GetString("VersionComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOOMB Internacional.
        /// </summary>
        public static string WOOMBInternational {
            get {
                return ResourceManager.GetString("WOOMBInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOOMB Latinoamérica.
        /// </summary>
        public static string WOOMBLA {
            get {
                return ResourceManager.GetString("WOOMBLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talleres.
        /// </summary>
        public static string Workshops {
            get {
                return ResourceManager.GetString("Workshops", resourceCulture);
            }
        }
    }
}
