//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC18 {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WC18.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Países afiliados.
        /// </summary>
        public static string Affiliates {
            get {
                return ResourceManager.GetString("Affiliates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Diseño Base.
        /// </summary>
        public static string BaseDesign {
            get {
                return ResourceManager.GetString("BaseDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizado por.
        /// </summary>
        public static string Customized {
            get {
                return ResourceManager.GetString("Customized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciencia de la fertilidad.
        /// </summary>
        public static string FertilityScience {
            get {
                return ResourceManager.GetString("FertilityScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conferencia WOOMB.
        /// </summary>
        public static string Headerhome {
            get {
                return ResourceManager.GetString("Headerhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conferencia Internacional del Metodo de Ovulacion Billings, WOOMB, Costa Rica 2018. Conferencia WOOMB. WOOMB Conference, Billings Ovulation Method..
        /// </summary>
        public static string HomeDesc {
            get {
                return ResourceManager.GetString("HomeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hospedaje cortesía de.
        /// </summary>
        public static string Hosting {
            get {
                return ResourceManager.GetString("Hosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de ID es requerido..
        /// </summary>
        public static string IdNumberRequired {
            get {
                return ResourceManager.GetString("IdNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de ID debe tener entre {2} y {1} caracteres..
        /// </summary>
        public static string IdNumberStringLength {
            get {
                return ResourceManager.GetString("IdNumberStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de ID es requerido..
        /// </summary>
        public static string IdTypeRequired {
            get {
                return ResourceManager.GetString("IdTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Charlas Inspiradoras.
        /// </summary>
        public static string InspiringPresentations {
            get {
                return ResourceManager.GetString("InspiringPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en.
        /// </summary>
        public static string LangComplement {
            get {
                return ResourceManager.GetString("LangComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información aquí.
        /// </summary>
        public static string LinkSponsors {
            get {
                return ResourceManager.GetString("LinkSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Programa.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Panelistas.
        /// </summary>
        public static string Speakers {
            get {
                return ResourceManager.GetString("Speakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patrocinadores.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrenamientos de instructores.
        /// </summary>
        public static string TeacherEducation {
            get {
                return ResourceManager.GetString("TeacherEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión Español.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English version.
        /// </summary>
        public static string VersionComplement {
            get {
                return ResourceManager.GetString("VersionComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WOOMB Internacional.
        /// </summary>
        public static string WOOMBInternational {
            get {
                return ResourceManager.GetString("WOOMBInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WOOMB Latinoamérica.
        /// </summary>
        public static string WOOMBLA {
            get {
                return ResourceManager.GetString("WOOMBLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talleres.
        /// </summary>
        public static string Workshops {
            get {
                return ResourceManager.GetString("Workshops", resourceCulture);
            }
        }
    }
}
