//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC18 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WC18.MainResources", typeof(MainResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Países afiliados.
        /// </summary>
        public static string Affiliates {
            get {
                return ResourceManager.GetString("Affiliates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseño Base.
        /// </summary>
        public static string BaseDesign {
            get {
                return ResourceManager.GetString("BaseDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalizado por.
        /// </summary>
        public static string Customized {
            get {
                return ResourceManager.GetString("Customized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciencia de la fertilidad.
        /// </summary>
        public static string FertilityScience {
            get {
                return ResourceManager.GetString("FertilityScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula.
        /// </summary>
        public static string FormGovermentID {
            get {
                return ResourceManager.GetString("FormGovermentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Tipo de ID -.
        /// </summary>
        public static string FormIDType {
            get {
                return ResourceManager.GetString("FormIDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasaporte.
        /// </summary>
        public static string FormPassport {
            get {
                return ResourceManager.GetString("FormPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferencia WOOMB.
        /// </summary>
        public static string Headerhome {
            get {
                return ResourceManager.GetString("Headerhome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferencia Internacional del Metodo de Ovulacion Billings, WOOMB, Costa Rica 2018. Conferencia WOOMB. WOOMB Conference, Billings Ovulation Method..
        /// </summary>
        public static string HomeDesc {
            get {
                return ResourceManager.GetString("HomeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospedaje cortesía de.
        /// </summary>
        public static string Hosting {
            get {
                return ResourceManager.GetString("Hosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de ID es requerido..
        /// </summary>
        public static string IdNumberRequired {
            get {
                return ResourceManager.GetString("IdNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de ID debe tener entre {2} y {1} caracteres..
        /// </summary>
        public static string IdNumberStringLength {
            get {
                return ResourceManager.GetString("IdNumberStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de ID es requerido..
        /// </summary>
        public static string IdTypeRequired {
            get {
                return ResourceManager.GetString("IdTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlas Inspiradoras.
        /// </summary>
        public static string InspiringPresentations {
            get {
                return ResourceManager.GetString("InspiringPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string LabelComments {
            get {
                return ResourceManager.GetString("LabelComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferencia.
        /// </summary>
        public static string LabelConference {
            get {
                return ResourceManager.GetString("LabelConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cena.
        /// </summary>
        public static string LabelDinner {
            get {
                return ResourceManager.GetString("LabelDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alojamiento (indicar número de noches).
        /// </summary>
        public static string LabelHost {
            get {
                return ResourceManager.GetString("LabelHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Días Alojamiento.
        /// </summary>
        public static string LabelHostDays {
            get {
                return ResourceManager.GetString("LabelHostDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de ID.
        /// </summary>
        public static string LabelIDNumber {
            get {
                return ResourceManager.GetString("LabelIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se inscribe para:.
        /// </summary>
        public static string LabelInscriptionFor {
            get {
                return ResourceManager.GetString("LabelInscriptionFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Trabaja en sector salud?.
        /// </summary>
        public static string LabelIsHealth {
            get {
                return ResourceManager.GetString("LabelIsHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Es Intructor?.
        /// </summary>
        public static string LabelIsIntructor {
            get {
                return ResourceManager.GetString("LabelIsIntructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Es usuario?.
        /// </summary>
        public static string LabelIsUser {
            get {
                return ResourceManager.GetString("LabelIsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour de medio día.
        /// </summary>
        public static string LabelTour {
            get {
                return ResourceManager.GetString("LabelTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamientos (Indicar en comentarios si básico/actualización o extensión).
        /// </summary>
        public static string LabelTrainings {
            get {
                return ResourceManager.GetString("LabelTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LangComplement {
            get {
                return ResourceManager.GetString("LangComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información aquí.
        /// </summary>
        public static string LinkSponsors {
            get {
                return ResourceManager.GetString("LinkSponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscripción.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panelistas.
        /// </summary>
        public static string Speakers {
            get {
                return ResourceManager.GetString("Speakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrocinadores.
        /// </summary>
        public static string Sponsors {
            get {
                return ResourceManager.GetString("Sponsors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrenamientos de instructores.
        /// </summary>
        public static string TeacherEducation {
            get {
                return ResourceManager.GetString("TeacherEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión Español.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English version.
        /// </summary>
        public static string VersionComplement {
            get {
                return ResourceManager.GetString("VersionComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOOMB Internacional.
        /// </summary>
        public static string WOOMBInternational {
            get {
                return ResourceManager.GetString("WOOMBInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOOMB Latinoamérica.
        /// </summary>
        public static string WOOMBLA {
            get {
                return ResourceManager.GetString("WOOMBLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talleres.
        /// </summary>
        public static string Workshops {
            get {
                return ResourceManager.GetString("Workshops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
